accident class base
marcelogaray/auto-GA-v03 pull request #18
Opened 2018-06-21 18:05 UTC by natalynanda

Base for start with accident cases

2018-06-21 18:06 UTC, natalynanda commented
@marcelogaray revisar por favor.

2018-06-21 23:30 UTC, marcelogaray requested changes
review observations

2018-06-21 23:30 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> +    @FindBy(xpath = "mat-dialog-4")
add blank line between  variables

2018-06-21 23:30 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> +    @FindBy(xpath = "mat-dialog-4")
review this locator

2018-06-21 23:30 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> +        try {
review CommentEvent otherwise create a new method

2018-06-21 23:30 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccidentFormModal.java
> +    @FindBy(xpath = "//*[@id='mat-dialog-1']/app-accident-new-form/form/mat-dialog-actions/button[2]")
improve this locator

2018-06-21 23:30 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/utils/CommonEvents.java
> +    public static boolean isAttributPresent(WebElement webElement, String attr) {
review this implementations

2018-06-22 00:39 UTC, natalynanda commented
@marcelogaray ok, fixed observations.

2018-06-22 13:25 UTC, natalynanda commented
Ing. Alguna observación después de mis correcciones?

El jue., jun. 21, 2018 7:30 PM, marcelogaray <notifications@github.com>
escribió:

> *@marcelogaray* requested changes on this pull request.
>
> review observations
> ------------------------------
>
> In
> src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#discussion_r197303861>
> :
>
> >  public class SHAccident extends BasePage {
> +    @FindBy(id = "RegistrarAccidente")
> +    private WebElement registrarAccBtn;
> +    @FindBy(xpath = "mat-dialog-4")
>
> add blank line between variables
> ------------------------------
>
> In
> src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#discussion_r197303916>
> :
>
> >  public class SHAccident extends BasePage {
> +    @FindBy(id = "RegistrarAccidente")
> +    private WebElement registrarAccBtn;
> +    @FindBy(xpath = "mat-dialog-4")
>
> review this locator
> ------------------------------
>
> In
> src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccident.java
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#discussion_r197304486>
> :
>
> >  public class SHAccident extends BasePage {
> +    @FindBy(id = "RegistrarAccidente")
> +    private WebElement registrarAccBtn;
> +    @FindBy(xpath = "mat-dialog-4")
> +    private WebElement nuevoRegistro;
> +
> +    public SHAccidentFormModal clickRegistarAccBtn() {
> +        if (CommonEvents.isClickable(registrarAccBtn)) {
> +            CommonEvents.clickButton(registrarAccBtn);
> +        }
> +        return new SHAccidentFormModal();
> +    }
> +
> +    public boolean isAccientePresent() {
> +        try {
>
> review CommentEvent otherwise create a new method
> ------------------------------
>
> In
> src/main/java/org/umssdiplo/automationv01/core/managepage/SHAccidentFormModal.java
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#discussion_r197304763>
> :
>
> > @@ -0,0 +1,67 @@
> +package org.umssdiplo.automationv01.core.managepage;
> +
> +import org.openqa.selenium.WebElement;
> +import org.openqa.selenium.support.FindBy;
> +import org.umssdiplo.automationv01.core.utils.CommonEvents;
> +
> +public class SHAccidentFormModal extends BasePage {
> +
> +    @FindBy(id = "mat-dialog-1")
> +    private WebElement modalDialog;
> +
> +    @FindBy(id = "btnClose")
> +    private WebElement closeBtn;
> +
> +    @FindBy(xpath = "//*[@id='mat-dialog-1']/app-accident-new-form/form/mat-dialog-actions/button[2]")
>
> improve this locator
> ------------------------------
>
> In src/main/java/org/umssdiplo/automationv01/core/utils/CommonEvents.java
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#discussion_r197305571>
> :
>
> > @@ -153,4 +153,12 @@ public static void waitUntil(long waitTime) {
>          }
>      }
>
> +    public static boolean isAttributPresent(WebElement webElement, String attr) {
>
> review this implementations
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marcelogaray/auto-GA-v03/pull/18#pullrequestreview-131024782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKqpWqwaI8BTs9Z2tc7uGXLo8SJ_11F7ks5t_CyFgaJpZM4Uyhue>
> .
>

2018-06-22 17:49 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/utils/CommonEvents.java
> +            return webElement.isDisplayed() ? isPresent(webElement) : false;
we are keeping this implementation. please avoid to use this type of logic, because it is just for this specific escenario.

2018-06-22 17:50 UTC, marcelogaray commented
Please we need to review it. I will close it and remark that I already reviewed this PR.
we are keeping this implementation. please avoid to use this type of logic, because it is just for this specific escenario.

2018-06-22 17:50 UTC, closed without merging